"use client";

import { useEffect, useMemo, useState } from "react";

type Status = "Ideias" | "Captação" | "Em edição" | "Revisão" | "Agendado" | "Publicado";
type Content = {
  id: string; title: string; date: string; format: string; funnel: string;
  pillar: string; status: Status; platforms: string[]; cta: string; notes: string;
};

const statusFlow: Status[] = ["Ideias", "Captação", "Em edição", "Revisão", "Agendado", "Publicado"];
const palette: Record<string, string> = { "Descoberta":"blue", "Consideração":"amber", "Conversão":"red", "Pós-venda":"violet", "Autoridade":"teal", "Confiança":"violet" };
const raw: [string,string,string,string,string,string][] = [
 ["2026-08-01","Estático","Manifesto: histórias transformadas em arte","Descoberta","Marca","Conheça a Forja"],["2026-08-02","Vídeo","Montagem rápida de várias peças prontas","Descoberta","Marca","Qual peça chamou você?"],
 ["2026-08-03","Estático","Carrossel: impressão 3D não significa produção em massa","Consideração","Autoridade","Salve para lembrar"],["2026-08-04","Vídeo","Close de pintura manual","Consideração","Autoridade","Veja os detalhes"],
 ["2026-08-05","Estático","Oxalá: significado e apresentação da peça","Descoberta","Guias e Orixás","Conheça a coleção"],["2026-08-06","Vídeo","Oxalá girando com detalhes","Descoberta","Guias e Orixás","Conheça a coleção"],
 ["2026-08-07","Estático","Antes e depois de um pet personalizado","Descoberta","Personalizados","Qual história você eternizaria?"],["2026-08-08","Vídeo","Foto do pet transformando-se em escultura","Descoberta","Personalizados","Solicite um orçamento"],
 ["2026-08-09","Estático","Dia dos Pais: presente personalizado","Conversão","Personalizados","Solicite um orçamento"],["2026-08-10","Vídeo","Peças masculinas e familiares em sequência","Conversão","Personalizados","Veja ideias de presente"],
 ["2026-08-11","Estático","Como funciona um projeto personalizado","Consideração","Personalizados","Envie sua ideia"],["2026-08-12","Vídeo","Referência, modelagem e peça pronta","Consideração","Autoridade","Conte sua ideia"],
 ["2026-08-13","Estático","Iemanjá: significado e detalhes","Descoberta","Guias e Orixás","Conheça a coleção"],["2026-08-14","Vídeo","Close cinematográfico de Iemanjá","Descoberta","Guias e Orixás","Qual detalhe mais chamou atenção?"],
 ["2026-08-15","Estático","Quanto detalhe cabe em uma peça pequena?","Consideração","Autoridade","Salve este post"],["2026-08-16","Vídeo","Macro da pintura e textura","Consideração","Autoridade","Veja o acabamento"],
 ["2026-08-17","Estático","Desenho infantil transformado em escultura","Descoberta","Personalizados","Transforme a imaginação"],["2026-08-18","Vídeo","Antes e depois do desenho infantil","Descoberta","Personalizados","Solicite um orçamento"],
 ["2026-08-19","Estático","FAQ: posso escolher as cores?","Consideração","Personalizados","Envie sua referência"],["2026-08-20","Vídeo","Mistura de tinta e aplicação","Consideração","Autoridade","Personalize sua peça"],
 ["2026-08-21","Estático","Ogum: força, caminhos e proteção","Descoberta","Guias e Orixás","Conheça a coleção"],["2026-08-22","Vídeo","Ogum em três ângulos","Descoberta","Guias e Orixás","Veja os detalhes"],
 ["2026-08-23","Estático","Depoimento de cliente","Pós-venda","Confiança","Veja histórias reais"],["2026-08-24","Vídeo","Peça sendo embalada para envio","Confiança","Confiança","Peça com envio nacional"],
 ["2026-08-25","Estático","Categorias de personalizados","Descoberta","Personalizados","Qual é a sua ideia?"],["2026-08-26","Vídeo","Montagem com pet, bebê, hobby e família","Descoberta","Personalizados","Conte sua história"],
 ["2026-08-27","Estático","Por que cada peça é única","Consideração","Autoridade","Conheça o processo"],["2026-08-28","Vídeo","Pequenas diferenças da pintura manual","Consideração","Autoridade","Veja o feito à mão"],
 ["2026-08-29","Estático","Chaveiros e ímãs: produtos de entrada","Conversão","Guias e Orixás","Veja as peças disponíveis"],["2026-08-30","Vídeo","Mão mostrando tamanho e acabamento","Conversão","Guias e Orixás","Escolha seu presente"],
 ["2026-08-31","Estático","Xangô: justiça, força e equilíbrio","Descoberta","Guias e Orixás","Conheça a coleção"],["2026-09-01","Vídeo","Xangô girando com iluminação dramática","Descoberta","Guias e Orixás","Veja os detalhes"],
 ["2026-09-02","Estático","Como enviamos a peça com segurança","Consideração","Confiança","Compre com confiança"],["2026-09-03","Vídeo","Embalagem completa em cortes rápidos","Consideração","Confiança","Envio para todo o Brasil"],
 ["2026-09-04","Estático","Crescimento do bebê: eternize cada fase","Descoberta","Personalizados","Conte essa história"],["2026-09-05","Vídeo","Três miniaturas de fases diferentes","Descoberta","Personalizados","Solicite um orçamento"],
 ["2026-09-06","Estático","Peça personalizada como presente","Conversão","Personalizados","Encontre o presente certo"],["2026-09-07","Vídeo","Reação simulada de abertura da caixa","Conversão","Personalizados","Transforme uma lembrança"],
 ["2026-09-08","Estático","Iansã: movimento, coragem e transformação","Descoberta","Guias e Orixás","Conheça a coleção"],["2026-09-09","Vídeo","Tecido, detalhes e movimento de câmera","Descoberta","Guias e Orixás","Veja os detalhes"],
 ["2026-09-10","Estático","FAQ: a peça pode quebrar?","Consideração","Confiança","Tire suas dúvidas"],["2026-09-11","Vídeo","Manuseio correto e embalagem","Consideração","Confiança","Veja como cuidamos"],
 ["2026-09-12","Estático","Modelo digital versus peça física","Autoridade","Autoridade","Veja o processo"],["2026-09-13","Vídeo","Tela do Blender passando para a escultura","Autoridade","Autoridade","Da ideia à peça"],
 ["2026-09-14","Estático","Caboclo Pena Branca: sabedoria e cura","Descoberta","Guias e Orixás","Conheça a coleção"],["2026-09-15","Vídeo","Close na pena, expressão e acabamento","Descoberta","Guias e Orixás","Veja os detalhes"],
 ["2026-09-16","Estático","Quanto trabalho existe em uma pequena escultura","Consideração","Autoridade","Salve para lembrar"],["2026-09-17","Vídeo","Time-lapse curto de pintura","Consideração","Autoridade","Veja o feito à mão"],
 ["2026-09-18","Estático","Personalizado para profissionais e conquistas","Descoberta","Personalizados","Conte sua conquista"],["2026-09-19","Vídeo","Referência profissional virando escultura","Descoberta","Personalizados","Solicite um orçamento"],
 ["2026-09-20","Estático","Vagas de produção para o próximo mês","Conversão","Personalizados","Reserve uma vaga"],["2026-09-21","Vídeo","Você trabalhando + chamada de orçamento","Conversão","Personalizados","Chame no WhatsApp"],
 ["2026-09-22","Estático","Preto Velho e Preta Velha: ancestralidade","Descoberta","Guias e Orixás","Conheça a coleção"],["2026-09-23","Vídeo","Duas peças lado a lado em movimento lento","Descoberta","Guias e Orixás","Veja os detalhes"],
 ["2026-09-24","Estático","O que o cliente aprova antes da produção","Consideração","Confiança","Entenda o processo"],["2026-09-25","Vídeo","Modelo 3D girando na tela","Consideração","Autoridade","Envie sua ideia"],
 ["2026-09-26","Estático","Coleção completa Guias e Orixás","Conversão","Guias e Orixás","Veja as peças disponíveis"],["2026-09-27","Vídeo","Travelling passando por todas as peças","Conversão","Guias e Orixás","Conheça a coleção"],
 ["2026-09-28","Estático","Qual história você transformaria em escultura?","Conversão","Marca","Conte sua ideia"],["2026-09-29","Vídeo","Compilado emocional dos melhores trabalhos","Conversão","Marca","Solicite um orçamento"]
];
const seed: Content[] = raw.map((x,i) => ({id:`forja-${i+1}`,date:x[0],format:x[1],title:x[2],funnel:x[3],pillar:x[4],cta:x[5],status:i<6?"Captação":i<12?"Em edição":i<18?"Revisão":"Agendado",platforms:x[1]==="Vídeo"?["Instagram","TikTok"]:["Instagram"],notes:""}));
const blank = ():Content => ({id:`novo-${Date.now()}`,title:"Novo conteúdo",date:"2026-08-01",format:"Vídeo",funnel:"Descoberta",pillar:"Personalizados",status:"Ideias",platforms:["Instagram"],cta:"",notes:""});
const fmtDate = (d:string) => new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short"}).format(new Date(`${d}T12:00:00`));

export default function Home(){
 const [contents,setContents]=useState<Content[]>(seed); const [active,setActive]=useState("Visão geral"); const [selected,setSelected]=useState<Content|null>(null); const [search,setSearch]=useState(""); const [month,setMonth]=useState("2026-08"); const [filter,setFilter]=useState("Todos");
 useEffect(()=>{const stored=localStorage.getItem("forja-content-v1"); if(stored) setContents(JSON.parse(stored));},[]);
 useEffect(()=>{localStorage.setItem("forja-content-v1",JSON.stringify(contents));},[contents]);
 const shown=useMemo(()=>contents.filter(c=>(filter==="Todos"||c.status===filter||c.funnel===filter||c.pillar===filter)&&`${c.title} ${c.format} ${c.pillar}`.toLowerCase().includes(search.toLowerCase())),[contents,filter,search]);
 const save=(item:Content)=>{setContents(old=>old.some(c=>c.id===item.id)?old.map(c=>c.id===item.id?item:c):[item,...old]);setSelected(null)};
 const move=(item:Content,status:Status)=>setContents(old=>old.map(c=>c.id===item.id?{...c,status}:c));
 const due=contents.filter(c=>c.status!=="Publicado"&&c.status!=="Agendado").length; const scheduled=contents.filter(c=>c.status==="Agendado").length; const videos=contents.filter(c=>c.format==="Vídeo").length;
 return <main className="shell">
   <aside className="sidebar"><div className="brand"><div className="brand-mark">F</div><div><b>FORJA</b><span>content studio</span></div></div><nav>{["Visão geral","Calendário","Fluxo de produção","Biblioteca","Resultados"].map(item=><button className={active===item?"nav active":"nav"} onClick={()=>setActive(item)} key={item}><span>{({"Visão geral":"◈","Calendário":"▦","Fluxo de produção":"↳","Biblioteca":"⌘","Resultados":"◌"} as Record<string,string>)[item]}</span>{item}</button>)}</nav><div className="side-note"><span>EM BREVE</span><b>Publicação integrada</b><p>Instagram, TikTok, YouTube e mais, em um só fluxo.</p></div><div className="profile"><div>FS</div><span>Forja do Sica<br/><small>estúdio criativo</small></span></div></aside>
   <section className="workspace"><header><div><p className="eyebrow">SISTEMA DE CONTEÚDO</p><h1>{active}</h1></div><div className="header-actions"><label className="search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar conteúdo" /></label><button className="primary" onClick={()=>setSelected(blank())}>+ Novo conteúdo</button></div></header>
   {active==="Visão geral"&&<Overview contents={contents} due={due} scheduled={scheduled} videos={videos} onOpen={setSelected} onGo={setActive}/>} 
   {active==="Fluxo de produção"&&<Board items={shown} onOpen={setSelected} onMove={move}/>} 
   {active==="Calendário"&&<Calendar contents={shown} month={month} setMonth={setMonth} onOpen={setSelected}/>} 
   {active==="Biblioteca"&&<Library items={shown} filter={filter} setFilter={setFilter} onOpen={setSelected}/>} 
   {active==="Resultados"&&<Results contents={contents}/>} 
   </section>{selected&&<Editor item={selected} onClose={()=>setSelected(null)} onSave={save} onDelete={()=>{setContents(x=>x.filter(c=>c.id!==selected.id));setSelected(null)}}/>}
 </main>
}

function Overview({contents,due,scheduled,videos,onOpen,onGo}:{contents:Content[],due:number,scheduled:number,videos:number,onOpen:(x:Content)=>void,onGo:(x:string)=>void}){const upcoming=contents.filter(c=>c.status!=="Publicado").slice(0,5);return <div className="page overview"><section className="hero"><div><p className="eyebrow light">PAINEL DA SEMANA</p><h2>A arte certa.<br/><em>No momento certo.</em></h2><p>Organize a produção, publique com consistência e acompanhe o que faz a Forja avançar.</p><button onClick={()=>onGo("Fluxo de produção")}>Abrir fluxo de produção →</button></div><div className="hero-orbit"><div className="orbit-line"></div><span className="orb o1">Ideia</span><span className="orb o2">Arte</span><span className="orb o3">Publicar</span><div className="orb-center">✦</div></div></section><section className="metric-row"><Metric n={due} label="em produção" tone="orange"/><Metric n={scheduled} label="agendados" tone="blue"/><Metric n={videos} label="vídeos no plano" tone="violet"/><Metric n={contents.length} label="conteúdos ativos" tone="dark"/></section><section className="split"><div className="panel"><div className="panel-title"><div><p className="eyebrow">PRÓXIMOS LANÇAMENTOS</p><h3>Na sua linha do tempo</h3></div><button onClick={()=>onGo("Calendário")}>Ver calendário</button></div><div className="timeline">{upcoming.map(item=><button className="timeline-row" key={item.id} onClick={()=>onOpen(item)}><time>{fmtDate(item.date)}</time><span className={`dot ${palette[item.funnel]||"blue"}`}></span><div><b>{item.title}</b><small>{item.format} · {item.pillar}</small></div><i>›</i></button>)}</div></div><div className="panel focus"><p className="eyebrow">FOCO OPERACIONAL</p><h3>Regra simples da semana</h3><p>Grave em lote. Uma sessão de duas horas deve render cenas para a semana inteira.</p><div className="focus-check"><span>✓</span><b>Peça girando</b><span>✓</span><b>Close de pintura</b><span>✓</span><b>Escala na mão</b></div></div></section></div>}
function Metric({n,label,tone}:{n:number,label:string,tone:string}){return <div className={`metric ${tone}`}><b>{n}</b><span>{label}</span></div>}
function Board({items,onOpen,onMove}:{items:Content[],onOpen:(x:Content)=>void,onMove:(x:Content,s:Status)=>void}){return <div className="page board-wrap"><div className="view-bar"><p>Arraste pelo fluxo mentalmente — altere o estágio pelo card para atualizar a produção.</p><select onChange={e=>{}}><option>Todos os pilares</option></select></div><div className="board">{statusFlow.map(status=>{const list=items.filter(x=>x.status===status);return <div className="column" key={status}><div className="column-head"><span className={`status-dot ${status.toLowerCase().replaceAll(" ","-")}`}></span><b>{status}</b><em>{list.length}</em></div>{list.map(item=><article className="content-card" key={item.id} onClick={()=>onOpen(item)}><div className="card-top"><span className={`chip ${palette[item.funnel]||"blue"}`}>{item.funnel}</span><span>{fmtDate(item.date)}</span></div><h4>{item.title}</h4><p>{item.format} · {item.pillar}</p><div className="card-foot"><div className="avatars">{item.platforms.map(p=><span key={p}>{p==="Instagram"?"◎":p==="TikTok"?"♪":"▶"}</span>)}</div><select value={item.status} onClick={e=>e.stopPropagation()} onChange={e=>onMove(item,e.target.value as Status)} aria-label="Alterar estágio"><option value="Ideias">Ideias</option><option value="Captação">Captação</option><option value="Em edição">Em edição</option><option value="Revisão">Revisão</option><option value="Agendado">Agendado</option><option value="Publicado">Publicado</option></select></div></article>)}<button className="add-card" onClick={()=>onOpen({...blank(),status})}>+ Adicionar</button></div>})}</div></div>}
function Calendar({contents,month,setMonth,onOpen}:{contents:Content[],month:string,setMonth:(x:string)=>void,onOpen:(x:Content)=>void}){const [year,m]=month.split("-").map(Number); const first=new Date(year,m-1,1); const blankDays=(first.getDay()+6)%7; const days=new Date(year,m,0).getDate(); const cells=[...Array(blankDays),...Array.from({length:days},(_,i)=>i+1)]; const name=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(first);return <div className="page calendar-page"><div className="calendar-top"><div><p className="eyebrow">PLANEJAMENTO EDITORIAL</p><h2>{name}</h2></div><div><button onClick={()=>setMonth(month==="2026-08"?"2026-09":"2026-08")}>↔ Trocar mês</button><button className="primary" onClick={()=>onOpen(blank())}>+ Criar neste mês</button></div></div><div className="weekday">{["SEG","TER","QUA","QUI","SEX","SÁB","DOM"].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{cells.map((day,i)=>{if(!day)return <div className="calendar-cell empty" key={i}/>;const date=`${month}-${String(day).padStart(2,"0")}`;const entries=contents.filter(x=>x.date===date);return <div className="calendar-cell" key={date}><b>{day}</b>{entries.map(x=><button onClick={()=>onOpen(x)} key={x.id} className={`cal-item ${palette[x.funnel]||"blue"}`}><span>{x.format==="Vídeo"?"▶":"▣"}</span>{x.title}</button>)}</div>})}</div></div>}
function Library({items,filter,setFilter,onOpen}:{items:Content[],filter:string,setFilter:(x:string)=>void,onOpen:(x:Content)=>void}){return <div className="page library"><div className="library-top"><div><p className="eyebrow">BANCO EDITÁVEL</p><h2>Todos os conteúdos</h2></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option>{statusFlow.map(x=><option key={x}>{x}</option>)}<option>Descoberta</option><option>Consideração</option><option>Conversão</option><option>Guias e Orixás</option><option>Personalizados</option></select></div><div className="data-table"><div className="data-head"><span>Conteúdo</span><span>Formato</span><span>Funil</span><span>Publicação</span><span>Estágio</span></div>{items.map(x=><button className="data-row" key={x.id} onClick={()=>onOpen(x)}><strong>{x.title}<small>{x.pillar} · {x.platforms.join(", ")}</small></strong><span>{x.format}</span><span className={`chip ${palette[x.funnel]||"blue"}`}>{x.funnel}</span><span>{fmtDate(x.date)}</span><span className="stage">{x.status}</span></button>)}</div></div>}
function Results({contents}:{contents:Content[]}){const funnels=["Descoberta","Consideração","Conversão","Pós-venda","Autoridade"];return <div className="page results"><section className="results-hero"><p className="eyebrow">VISÃO DE RESULTADOS</p><h2>O que deve ser medido<br/>depois de publicar.</h2><p>Este é o espaço para a próxima fase: registrar alcance, retenção, salvamentos, cliques e pedidos recebidos por conteúdo.</p></section><section className="funnel-stats">{funnels.map(f=>{const n=contents.filter(c=>c.funnel===f).length;return <div key={f}><span className={`dot ${palette[f]||"blue"}`}></span><b>{n}</b><small>{f}</small><div><i style={{width:`${Math.max(n*5,12)}%`}}></i></div></div>})}</section><div className="integration-card"><div className="integration-icon">↗</div><div><p className="eyebrow">PRÓXIMA EVOLUÇÃO</p><h3>Publicar, agendar e medir no mesmo lugar.</h3><p>A estrutura já guarda plataforma, data e estágio. A próxima camada pode conectar contas sociais, subir arquivos e enviar conteúdos para agendamento.</p></div><span>planejado</span></div></div>}
function Editor({item,onClose,onSave,onDelete}:{item:Content,onClose:()=>void,onSave:(x:Content)=>void,onDelete:()=>void}){const [draft,setDraft]=useState(item);const change=(key:keyof Content,value:any)=>setDraft(x=>({...x,[key]:value}));const platform=(name:string)=>change("platforms",draft.platforms.includes(name)?draft.platforms.filter(x=>x!==name):[...draft.platforms,name]);return <div className="modal-backdrop" onMouseDown={onClose}><section className="editor" onMouseDown={e=>e.stopPropagation()}><header><div><p className="eyebrow">FICHA DO CONTEÚDO</p><h2>Editar criação</h2></div><button className="close" onClick={onClose}>×</button></header><div className="editor-body"><label className="full">Título<input value={draft.title} onChange={e=>change("title",e.target.value)}/></label><div className="form-grid"><label>Data de publicação<input type="date" value={draft.date} onChange={e=>change("date",e.target.value)}/></label><label>Formato<select value={draft.format} onChange={e=>change("format",e.target.value)}><option>Vídeo</option><option>Estático</option><option>Carrossel</option><option>Story</option></select></label><label>Etapa do fluxo<select value={draft.status} onChange={e=>change("status",e.target.value)}>{statusFlow.map(x=><option key={x}>{x}</option>)}</select></label><label>Funil<select value={draft.funnel} onChange={e=>change("funnel",e.target.value)}>{["Descoberta","Consideração","Conversão","Pós-venda","Autoridade","Confiança"].map(x=><option key={x}>{x}</option>)}</select></label><label className="full">Pilar<select value={draft.pillar} onChange={e=>change("pillar",e.target.value)}>{["Guias e Orixás","Personalizados","Autoridade","Confiança","Marca"].map(x=><option key={x}>{x}</option>)}</select></label></div><fieldset><legend>Plataformas</legend>{["Instagram","TikTok","YouTube"].map(p=><label className="toggle" key={p}><input type="checkbox" checked={draft.platforms.includes(p)} onChange={()=>platform(p)}/><span></span>{p}</label>)}</fieldset><label className="full">CTA<input value={draft.cta} onChange={e=>change("cta",e.target.value)} placeholder="Ex.: Solicite um orçamento"/></label><label className="full">Roteiro, referências e observações<textarea value={draft.notes} onChange={e=>change("notes",e.target.value)} placeholder="Cena, texto na tela, link de referência, observações de produção..."/></label></div><footer><button className="delete" onClick={onDelete}>Excluir</button><div><button onClick={onClose}>Cancelar</button><button className="primary" onClick={()=>onSave(draft)}>Salvar alterações</button></div></footer></section></div>}
