/** Pauta editorial original da Forja do Sica (data, formato, titulo, funil, pilar, cta). */
export const FORJA_PLAN: [string,string,string,string,string,string][] = [
  ["2026-08-10","Estático","Manifesto: histórias transformadas em arte","Descoberta","Marca","Conheça a Forja"],
  ["2026-08-11","Vídeo","Montagem rápida de várias peças prontas","Descoberta","Marca","Qual peça chamou você?"],
  ["2026-08-12","Estático","Carrossel: impressão 3D não significa produção em massa","Consideração","Autoridade","Salve para lembrar"],
  ["2026-08-13","Vídeo","Close de pintura manual","Consideração","Autoridade","Veja os detalhes"],
  ["2026-08-14","Estático","Oxalá: significado e apresentação da peça","Descoberta","Guias e Orixás","Conheça a coleção"],
  ["2026-08-15","Vídeo","Oxalá girando com detalhes","Descoberta","Guias e Orixás","Conheça a coleção"],
  ["2026-08-16","Estático","Antes e depois de um pet personalizado","Descoberta","Personalizados","Qual história você eternizaria?"],
  ["2026-08-17","Vídeo","Foto do pet transformando-se em escultura","Descoberta","Personalizados","Solicite um orçamento"],
  ["2026-08-19","Vídeo","Peças masculinas e familiares em sequência","Conversão","Personalizados","Veja ideias de presente"],
  ["2026-08-20","Estático","Como funciona um projeto personalizado","Consideração","Personalizados","Envie sua ideia"],
  ["2026-08-21","Vídeo","Referência, modelagem e peça pronta","Consideração","Autoridade","Conte sua ideia"],
  ["2026-08-22","Estático","Iemanjá: significado e detalhes","Descoberta","Guias e Orixás","Conheça a coleção"],
  ["2026-08-23","Vídeo","Close cinematográfico de Iemanjá","Descoberta","Guias e Orixás","Qual detalhe mais chamou atenção?"],
  ["2026-08-24","Estático","Quanto detalhe cabe em uma peça pequena?","Consideração","Autoridade","Salve este post"],
  ["2026-08-25","Vídeo","Macro da pintura e textura","Consideração","Autoridade","Veja o acabamento"],
  ["2026-08-26","Estático","Desenho infantil transformado em escultura","Descoberta","Personalizados","Transforme a imaginação"],
  ["2026-08-27","Vídeo","Antes e depois do desenho infantil","Descoberta","Personalizados","Solicite um orçamento"],
  ["2026-08-28","Estático","FAQ: posso escolher as cores?","Consideração","Personalizados","Envie sua referência"],
  ["2026-08-29","Vídeo","Mistura de tinta e aplicação","Consideração","Autoridade","Personalize sua peça"],
  ["2026-08-30","Estático","Ogum: força, caminhos e proteção","Descoberta","Guias e Orixás","Conheça a coleção"],
  ["2026-08-31","Vídeo","Ogum em três ângulos","Descoberta","Guias e Orixás","Veja os detalhes"],
  ["2026-09-01","Estático","Depoimento de cliente","Pós-venda","Confiança","Veja histórias reais"],
  ["2026-09-02","Vídeo","Peça sendo embalada para envio","Confiança","Confiança","Peça com envio nacional"],
  ["2026-09-03","Estático","Categorias de personalizados","Descoberta","Personalizados","Qual é a sua ideia?"],
  ["2026-09-04","Vídeo","Montagem com pet, bebê, hobby e família","Descoberta","Personalizados","Conte sua história"],
  ["2026-09-05","Estático","Por que cada peça é única","Consideração","Autoridade","Conheça o processo"],
  ["2026-09-06","Vídeo","Pequenas diferenças da pintura manual","Consideração","Autoridade","Veja o feito à mão"],
  ["2026-09-07","Estático","Chaveiros e ímãs: produtos de entrada","Conversão","Guias e Orixás","Veja as peças disponíveis"],
  ["2026-09-08","Vídeo","Mão mostrando tamanho e acabamento","Conversão","Guias e Orixás","Escolha seu presente"],
  ["2026-09-09","Estático","Xangô: justiça, força e equilíbrio","Descoberta","Guias e Orixás","Conheça a coleção"],
  ["2026-09-10","Vídeo","Xangô girando com iluminação dramática","Descoberta","Guias e Orixás","Veja os detalhes"],
  ["2026-09-11","Estático","Como enviamos a peça com segurança","Consideração","Confiança","Compre com confiança"],
  ["2026-09-12","Vídeo","Embalagem completa em cortes rápidos","Consideração","Confiança","Envio para todo o Brasil"],
  ["2026-09-13","Estático","Crescimento do bebê: eternize cada fase","Descoberta","Personalizados","Conte essa história"],
  ["2026-09-14","Vídeo","Três miniaturas de fases diferentes","Descoberta","Personalizados","Solicite um orçamento"],
  ["2026-09-15","Estático","Peça personalizada como presente","Conversão","Personalizados","Encontre o presente certo"],
  ["2026-09-16","Vídeo","Reação simulada de abertura da caixa","Conversão","Personalizados","Transforme uma lembrança"],
  ["2026-09-17","Estático","Iansã: movimento, coragem e transformação","Descoberta","Guias e Orixás","Conheça a coleção"],
  ["2026-09-18","Vídeo","Tecido, detalhes e movimento de câmera","Descoberta","Guias e Orixás","Veja os detalhes"],
  ["2026-09-19","Estático","FAQ: a peça pode quebrar?","Consideração","Confiança","Tire suas dúvidas"],
  ["2026-09-20","Vídeo","Manuseio correto e embalagem","Consideração","Confiança","Veja como cuidamos"],
  ["2026-09-21","Estático","Modelo digital versus peça física","Autoridade","Autoridade","Veja o processo"],
  ["2026-09-22","Vídeo","Tela do Blender passando para a escultura","Autoridade","Autoridade","Da ideia à peça"],
  ["2026-09-23","Estático","Caboclo Pena Branca: sabedoria e cura","Descoberta","Guias e Orixás","Conheça a coleção"],
  ["2026-09-24","Vídeo","Close na pena, expressão e acabamento","Descoberta","Guias e Orixás","Veja os detalhes"],
  ["2026-09-25","Estático","Quanto trabalho existe em uma pequena escultura","Consideração","Autoridade","Salve para lembrar"],
  ["2026-09-26","Vídeo","Time-lapse curto de pintura","Consideração","Autoridade","Veja o feito à mão"],
  ["2026-09-27","Estático","Personalizado para profissionais e conquistas","Descoberta","Personalizados","Conte sua conquista"],
  ["2026-09-28","Vídeo","Referência profissional virando escultura","Descoberta","Personalizados","Solicite um orçamento"],
  ["2026-09-29","Estático","Vagas de produção para o próximo mês","Conversão","Personalizados","Reserve uma vaga"],
  ["2026-09-30","Vídeo","Você trabalhando + chamada de orçamento","Conversão","Personalizados","Chame no WhatsApp"],
  ["2026-10-01","Estático","Preto Velho e Preta Velha: ancestralidade","Descoberta","Guias e Orixás","Conheça a coleção"],
  ["2026-10-02","Vídeo","Duas peças lado a lado em movimento lento","Descoberta","Guias e Orixás","Veja os detalhes"],
  ["2026-10-03","Estático","O que o cliente aprova antes da produção","Consideração","Confiança","Entenda o processo"],
  ["2026-10-04","Vídeo","Modelo 3D girando na tela","Consideração","Autoridade","Envie sua ideia"],
  ["2026-10-05","Estático","Coleção completa Guias e Orixás","Conversão","Guias e Orixás","Veja as peças disponíveis"],
  ["2026-10-06","Vídeo","Travelling passando por todas as peças","Conversão","Guias e Orixás","Conheça a coleção"],
  ["2026-10-07","Estático","Qual história você transformaria em escultura?","Conversão","Marca","Conte sua ideia"],
  ["2026-10-08","Vídeo","Compilado emocional dos melhores trabalhos","Conversão","Marca","Solicite um orçamento"],
];
